### ISSUE TITLE
Use proper icon

### ISSUE THREAD

**Issue by connor** [domainr/domainr-mac#20]
![icon-1024x1024-no-alpha](https://cloud.githubusercontent.com/assets/97697/5604139/2666eede-9377-11e4-9dfc-ec221a31afe7.png)

**Comment by connor** [comment]
Yo @ydnar / @case – do you have a source file for this? I've got the png but would love a Sketch/PS file if there is one.

**Comment by case** [comment]
@connor here are the files we found:

http://cl.ly/1u0b3M1R0i08

**Comment by connor** [comment]
:heart:
